
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjyeqltwvlhexgncudpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqeWVxbHR3dmxoZXhnbmN1ZHB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NzEzNDcsImV4cCI6MjA2NzE0NzM0N30.WS4JkJYCUaFxuimqDbnA7mPO1Syb6xH0gkNhus4gE_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
